# Generated by Django 3.1 on 2020-11-06 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201106_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
    ]
