# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  services:
    postgres:
      image: postgres:10.8
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: github_actions
      ports:
        - 5432:5432
      # needed because the postgres container does not provide a healthcheck
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: psycopg2 prerequisitos
      run: sudo apt-get install python-dev libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run tests
      run: python manage.py test blog.tests.test_models.PublicacionModelTest
